# Generated by Django 3.1.7 on 2021-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_auto_20210426_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=245)),
                ('file_size', models.CharField(max_length=245)),
                ('file_type', models.CharField(max_length=245)),
            ],
        ),
    ]
