# Generated by Django 3.1.7 on 2021-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_file_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_details',
        ),
        migrations.AddField(
            model_name='upload_model',
            name='file_name',
            field=models.CharField(max_length=245, null=True),
        ),
        migrations.AddField(
            model_name='upload_model',
            name='file_size',
            field=models.CharField(max_length=245, null=True),
        ),
        migrations.AddField(
            model_name='upload_model',
            name='file_type',
            field=models.CharField(max_length=245, null=True),
        ),
    ]
