# Generated by Django 3.1.7 on 2021-04-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_auto_20210426_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_model',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
